AdminPlatfform.Web/Controllers/AdminController.cs
using AdminPlatfform;
using AdminPlatfform.Web;
using AdminPlatfform.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UserReg.Controllers
{
    /// <summary>
    /// Die Controller wird die Logik von Login einem Admin in Anwnendung implementiert
    /// </summary>

    public class AdminController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// Hier wurde die Daten bei Login wie Username und Password überprüft, ob es stimmt ist oder nicht 
        //  Hier wurde die Datenbank abgeruft um die Index zu holen.
        /// </summary>
        /// <param name="AdminModel"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Autherize(Admin_Geschäftfuehrer AdminModel)
        {
            using (AdminEntities db = new AdminEntities())
            {
                var userDetails = db.Admin_Geschäftfuehrer.Where(x => x.Username == AdminModel.Username && x.Password== AdminModel.Password).FirstOrDefault();
                if (userDetails == null)
                {
                    AdminModel.LoginErrorMessage = "Überprüfen Sie Ihre Daten nach bitte ! ";
                    return View("Index", AdminModel);
                }
                else
                  Session["UserID"] = userDetails.Admin_id;
                return View("~/Views/FirstLayout/Index.cshtml", AdminModel);
            }
        }
    }
}

AdminPlatfform.Web/Controllers/AdminEngController.cs
using AdminPlatfform.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminPlatfform.Web.Controllers
{
    /// <summary>
    /// Controller für Registrieren einem Admin 
    /// </summary>
    public class AdminEngController : Controller
    {
        // GET: AdminEng
        // Database 
        AdminEntities _db;
        public AdminEngController()
        {
            _db = new AdminEntities();
        }
       
        // GET: AdminEng
        public ActionResult Index()
        {
            return View();
        }
        // GET: AdminEng
        public ActionResult AddOrEdit(int id = 0)
        {
            Admin_Geschäftfuehrer userModel = new Admin_Geschäftfuehrer();
            return View(userModel);
        }
        // POST Methode indem wurde die Geschäftslogik einer neue Registrieren implementiert 
        // Database wurde abgeruft 
        [HttpPost]
        public ActionResult AddOrEdit(Admin_Geschäftfuehrer userModel)
        {
            using (AdminEntities model = new AdminEntities())
            {
                model.Admin_Geschäftfuehrer.Add(userModel);
               model.SaveChanges();
            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Registration Successful ";
            return View("AddOrEdit", new Admin_Geschäftfuehrer());
        }
    }
}

AdminPlatfform.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminPlatfform.Web.Controllers
{
    /// <summary>
    ///  Controller indem wirde die View von HomePage zurückgegeben 
    /// </summary>
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

AdminPlatfform.Web/Views/Home/Index.cshtml
@model AdminPlatfform.Web.Models.Admin_Geschäftfuehrer

@*View Home*@

@{
    ViewBag.Title = "Login";
}
@* CSS Code  *@
<style>
    .field-validation-error {
        color: red;
    }

    .all
    {
        padding-left: 450px;
        padding-top: 170px;
        text-align: center;
        display: inline-block;
    }

    body, html {
        height: 100%;
    }

    body, html {
        /* The image used */
        background-image: url("../../images/galymzhan-abdugalimov-ICW6QYOcdlg-unsplash.jpg");
        /* Full height */
        /* Center and scale the image nicely */
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }
    .field-validation-error {
        color: red;
    }
    .allbutton {
        margin-left: 5px;
    }

    h2 {
        color: white;
        padding-left: 40px;
    }

    #a1 {
        color: white;
    }

    #bild {
        margin-left: 15px;
        padding-left: 15px;
    }
</style>
@* HTML Komponenten *@
<body>
    <div class="all">
        <h2>Login as Admin</h2>


        @using (Html.BeginForm("Autherize", "Admin", FormMethod.Post))
        {
            @Html.AntiForgeryToken()


            <div id="a1">@Html.LabelFor(model => model.Username)</div>

            @Html.EditorFor(model => model.Username)

            <p>@Html.ValidationMessageFor(model => model.Username)</p>

            <div class="input-div two">
                <div class="i">
                    <i class="fas fa-lock"></i>
                </div>
                <div>
                    <div id="a1">@Html.LabelFor(model => model.Password)</div>
                    @Html.EditorFor(model => model.Password)
                </div>

                <p>@Html.ValidationMessageFor(model => model.Password)</p>
            </div>
            <div class="allbutton">
                <input type="submit" id="button" class="btn" name="name" value="Login" />
                <a href="@Url.Action("AddOrEdit", "AdminEng")" class="btn btn-primary">Registieren</a>
                <label class="field-validation-error">@Html.DisplayFor(model => model.LoginErrorMessage)</label>

            </div>
        }
    </div>
</body>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}