JahresUrlaub.Web/Controllers/FirstPageController.cs
using JahresUrlaub.Web.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace JahresUrlaub.Web.Controllers
{
    /// <summary>
    /// First Page nach Login 
    /// </summary>
    public class FirstPageController : Controller
    {
        EventsEntities _db; 
        public FirstPageController()
        {
            _db = new EventsEntities(); 
        }
     
        // GET: FirstPage
        public ActionResult Index()
        {
            
            return View(); 
        }
        public JsonResult GetEvents()
        {
            using (EventsEntities dc = new EventsEntities())
            {

                var events = dc.Events.ToList();
                return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }
    }
}

JahresUrlaub.Web/Controllers/UrlaubController.cs
using JahresUrlaub.Web.Models;
using Limilabs.Client.SMTP;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace JahresUrlaub.Web.Controllers
{
    public class UrlaubController : Controller
    {
        // GET: Home
        /// <summary>
        ///   <para>GET : Home DataEvent für Kalender</para>
        ///   <para>return View(); </para>
        /// </summary>

        public UrlaubController()
        {
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Edit()
        {
            return View();
        }
        public JsonResult GetUrlaubs()
        {
            using (EventsEntities dc = new EventsEntities())
            {   
                        var urlaubs = dc.Events.ToList();
                        return new JsonResult { Data = urlaubs, JsonRequestBehavior = JsonRequestBehavior.AllowGet };          
             }
           
        }
        [HttpPost]
        public JsonResult SaveUrlaub(Events e)
        {
            var status = false;
            using (EventsEntities dc = new EventsEntities())
            {
                if (e.EventID > 0)
                {
                    ///Update the event
                    var v = dc.Events.Where(a => a.EventID == e.EventID).FirstOrDefault();
                    if (v != null)
                    {
                        v.Subject = e.Subject;
                        v.Start = e.Start;
                        v.End= e.End;
                        v.Description = e.Description;
                        
                        v.ThemeColor = e.ThemeColor;
                    }
                }
                else
                {
                    dc.Events.Add(e);
                }

                dc.SaveChanges();
                SendVerificationLinkEmail();

                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }
        [NonAction]
        public void SendVerificationLinkEmail()
        {
            string email = "azlouknourddin@gmail.com"; // Email_Chef
            
            var fromEmail = new MailAddress("azlouknour@gmail.com", "Urlaubsverwaltung");
            var toEmail = new MailAddress(email);
            var fromEmailPassword = "testpassword";
            string subject = "Neuer Antrag ist eingegangen!";
            string body = "<br/><br/> In Ihrem Urlaubsverwaltungskonto ist ein neuer Urlaubsantrag Ihres Mitarbeiters eingegangen." +
                "<br/><br/>"+
                "Mit freundlichen Grüßen";
                
            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
            };
            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
                smtp.Send(message);
        }
        /// <summary>Deletes the event.</summary>
        /// <param name="EventID">The event identifier.</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult DeleteUrlaub(int EventID)
        {
            /// <summary>
            /// Implements the DeleteEvent method.
            /// </summary>
            /// <returns>Memeful Comments</returns>
            /// <image url="https://media.giphy.com/media/Ca7gy6EZqdH32/giphy.gif" scale="0.3" />

            var status = false;
            using (EventsEntities dc = new EventsEntities())
            {
                var v = dc.Events.Where(a => a.EventID == EventID).FirstOrDefault();
                if (v != null)
                {
                    dc.Events.Remove(v);
                    dc.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }
    }
}

JahresUrlaub.Web/Views/FirstPage/Index.cshtml
@* FirstPage nach einloggen von Mitarbeiter *@


    <html>
    @{
        ViewBag.Title = "FirstPage";
    }
    @* CSS Code  *@
    <style>
        .vl {
            border-left: 6px solid green;
            margin-top: 20px;
            margin-left: 80px;
        }

        #bild {
            margin-right: 100px;
            margin-top: 70px;
            margin-bottom:-30px;
        }

        .allbutton {
            margin-right: 5px;
            margin-left: 20px;
            margin-top: 70px;
        }

        #username {
            margin-top: -1px;
        }

        #bild1 {
            width: 500px;
            height: 400px;
            margin-left: 200px;
            margin-top: 40px;
        }

        #GruppElement {
            margin-left: 60px;
            margin-top: 50px;
        }

        .btn {
            margin-top: 10px;
            margin-right: -10px;
        }

        #addbild1 {
            margin-left: 20px;
            ;
        }

        #GruppElement1 {
            margin-left: 380px;
            margin-top: -145px;
        }

        #GruppElement2 {
            margin-left: 700px;
            margin-top: -145px;
        }

        html, body {
            height: 100%;
        }

        body, html {
            /* The image used */
            background-image: url('../../Images/aaron-huber---WbZltaVww-unsplash.jpg');
            /* Full height */
            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }

        #out {
            margin-left: 1000px;
        }
        #GruppElement3 {
            margin-left: 1000px;
            margin-top: -145px;
        }
        #btt4 {
            margin-left: 20px;
        }
        h5{
            padding-top:-50px;
            padding-left:20px;
            color:black;
            font-weight:bold;
            font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
    </style>
    @* HTML Komponenten wie Input und Label *@
    <body>

        <img src="~/Images/profile.png" width="80" height="50" id="bild" />


        @using (Html.BeginForm("Logout", "Login", FormMethod.Post))
        {

            <input id="out" type="submit" value="Logout" class="btn btn-default" />
        }
        @if (Session["UserID"] != null)
        {


            <h5> Herzlich Willkomen @Session["Lastname"].ToString()</h5>
            <span id="all">
                <div id="GruppElement">
                    <img src="~/Images/add.png" id="addbild1" width="100" height="100" />

                    <br />
                    <a href="@Url.Action("Index", "Urlaub")" class="btn btn-success">Urlaub-beantragen</a>
                </div>
                <div id="GruppElement1">
                    <img src="~/Images/folder.png" id="addbild1" width="100" height="100" />
                    <br />
                    <a href="@Url.Action("Status", "Status")" class="btn btn-success">Urlaub-Status</a>
                </div>
                <div id="GruppElement2">
                    <img src="~/Images/paket.png" id="addbild1" width="100" height="100" />
                    <br />
                    <a href="@Url.Action("Edit", "Urlaub")" class="btn btn-success">Urlaub-bearbeiten</a>
                </div>
                <div id="GruppElement3">
                    <img src="~/Images/notification.png" id="addbild1" width="100" height="100" />
                    <br />
                    <a href="https://localhost:44354/" class="btn btn-success" id="btt4">Notifikation</a>
                </div>


            </span>
        }
    </body>
</html>

<!-- Kalendar Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Status</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">


                <form method="get" asp-action="Index">
                    <p>
                        <input type="search" placeholder="Suchen..." value="@ViewData["Getdetais"]" name="searchString" style="width:500px;" />
                        <input type="submit" value="Search" class="btn btn-primary" />

                    </p>
                    <!-- Ajax -- Schnittstelle mit Controller -->
                    <script>
                        $(document).ready(function () {
                            var events = [];
                            var selectedEvent = null;
                            FetchEventAndRenderCalendar();
                            function FetchEventAndRenderCalendar() {
                                events = [];
                                $.ajax({
                                    type: "GET",
                                    url: "/UFirstPage/GetEvents",
                                    success: function (data) {
                                        $.each(data, function (i, v) {
                                            events.push({
                                                eventID: v.EventID,
                                                title: v.Subject,
                                                description: v.Description,
                                                start: moment(v.Start),
                                                end: v.End != null ? moment(v.End) : null,
                                                color: v.ThemeColor,
                                                allDay: v.IsFullDay
                                            });
                                        })

                                        GenerateCalender(events);
                                    },
                                    error: function (error) {
                                        alert('failed');
                                    }
                                })
                            }
                    </script>
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
        