JahresUrlaub.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JahresUrlaub.Web.Controllers
{ 
    /// <summary>
    /// Home Page für Ganz Anwendung
    /// </summary>
    public class HomeController : Controller
    {
       // GET:HOME
        public ActionResult Index()
        {
           return View();
        }
    }
}

JahresUrlaub.Web/Controllers/RegistierenController.cs
using DocumentFormat.OpenXml.Wordprocessing;
using JahresUrlaub.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace JahresUrlaub.Web.Controllers
{
    /// <summary>
    /// Registrieren Logik für neue Mitarbeiter 
    /// </summary>
    public class RegistierenController : Controller
    {
        UserEntities _db;
        public RegistierenController()
        {
            _db = new UserEntities();
        }
        // Registrion Action 
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }
        // Registration POST Action 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add([Bind(Exclude = "IsEmailVerified,ActivationCode")] Users users)
        {
            bool Status = false;
            string message = "";
            //
            // Model Validation 
            if (ModelState.IsValid)
            {

                #region //Email is alerdy Exist 
                var isExist = IsEmailExist(users.Email);
                if (isExist)
                {
                    ModelState.AddModelError("EmailExist", "Email bereit raus");
                    return View(users);
                }
                #endregion
                #region Generate Activation Code
                users.ActivationCode = Guid.NewGuid();
                #endregion

                #region Password Hashing 
                users.Password = Crypto.Hash(users.Password);
                users.ConfirmPassword = Crypto.Hash(users.ConfirmPassword); 
                #endregion
                users.IsEmailVerified = false;
                #region Save to Database 
                using (UserEntities _db = new UserEntities())
                {
                     
                    _db.Users.Add(users);
                    _db.SaveChanges();

                    //send Email to user 
                    SendVerificationLinkEmail(users.Email, users.ActivationCode.ToString());
                    message = "Registration erfolgreich Konto Aktiviation Link" +
                        " Email wurd an Ihre Email breits gesendet  " + users.Email;
                    Status = true;
                }
                #endregion
            }
            else
            {
                message = "Fehermeldung";
            }
            // Email is Bereits RAUS 

            // Generate Actiovation Code 
            // Password Hashing 

            // Save data to Database

            // Send Email to User 
            ViewBag.Message = message;
            ViewBag.Status = Status;
            return View(users);
        }
        //Verif Account
        [HttpGet]
        public ActionResult VerifyAccount(string id)
        {   
            bool Status = false;
            using(UserEntities db = new UserEntities())
            {
                db.Configuration.ValidateOnSaveEnabled = false;
                var v = db.Users.Where(x => x.ActivationCode == new Guid(id)).FirstOrDefault();
                if(v!=null)
                {
                    v.IsEmailVerified = true;
                    db.SaveChanges();
                    Status = true;
                }
                else
                {
                    ViewBag.Message = "Fehlermeldung";
                }
            }
            ViewBag.Status = Status;
            return View();
        }
        // Verfiy Email LINK
        [NonAction]
        public bool IsEmailExist(string email)
        {
            using (UserEntities user = new UserEntities())
            {
                var v = user.Users.Where(a => a.Email == email).FirstOrDefault();
                return v != null;
            }
        }
        [NonAction]
        public void SendVerificationLinkEmail(string email, string activiationCode)
        {
            var verifyUrl = "/Registieren/VerifyAccount/" + activiationCode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);
            var fromEmail = new MailAddress("azlouknour@gmail.com", "Urlaubsverwaltung");
            var toEmail = new MailAddress(email);
            var fromEmailPassword = "testpassword"; 
            string subject = "Your account is successfully created!";
            string body = "<br/><br/>Wir freuen uns, Ihnen mitteilen zu können, dass Ihr Urlaubsverwaltung-Konto erfolgreich erstellt wurde." +
                " Bitte klicken Sie auf den folgenden Link, um Ihr Konto zu bestätigen" +
                " <br/><br/><a href='" + link + "'>" + link + "</a> ";
            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
            };
            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
                smtp.Send(message);
        }
    }
}

JahresUrlaub.Web/Views/Home/Index.cshtml
@* Home Page View der Anwendung *@
@model JahresUrlaub.Web.Models.Users


@{
    ViewBag.Title = "Login";
}
@* CSS Code  *@
<style>
    h2 {
        color: white;
        padding-left: 25px;
    }

    .all {
        padding-left: 450px;
        padding-top: 170px;
        text-align: center;
        display: inline-block;
    }

    .field-validation-error {
        color: red;
        font-weight: bold;
        font-family: Bahnschrift;
        padding-left: 20px;
    }

    body, html {
        height: 100%;
    }

    body, html {
        /* The image used */
        background-image: url("../../Images/krakenimages-376KN_ISplE-unsplash.jpg");
        /* Full height */
        /* Center and scale the image nicely */
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }
    #error {
        color: red;
        font-weight: bold;
    }
    .allbutton {
        padding-left: 50px;
    }
    #pass{
        margin-right:27px;
    }
    #vergessen{
        margin-top:10px;
        margin-left:30px;
        color:blanchedalmond;
    }
    h1 
    {
           color:white;
           font-weight:bold;
           font-size:medium;
    }
</style>
@* HTML-Elements  *@
<body>
    <div class="all">
        <h2>Login</h2>


        @using (Html.BeginForm("Login", "Login", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div>
                @Html.LabelFor(model => model.Email)
                @Html.EditorFor(model => model.Email)
            </div>
            <p>@Html.ValidationMessageFor(model => model.Email)</p>

            <div class="input-div two">
                <div class="i">
                    <i class="fas fa-lock"></i>
                </div>
                <div id="pass">
                    <label>Password</label>
                    @Html.EditorFor(model => model.Password)
                </div>

                <p>@Html.ValidationMessageFor(model => model.Password)</p>
            </div>

            <div class="allbutton">
                <input type="submit" id="button" class="btn" name="name" value="Login" />
                <a href="@Url.Action("Add", "Registieren")" class="btn btn-primary">Registieren</a>
                <label class="field-validation-error">@Html.DisplayFor(model => model.LoginErrorMessage)</label>
            </div>
            <div id="vergessen">
                <h1>@Html.ActionLink("Password vergessen", "ForgotPassword", "Login")</h1>
            </div>
            <label id="error">@ViewBag.Error</label>

        }
    </div>
</body>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}